// interface provider
export interface PropsProvider {
    children: JSX.Element | JSX.Element[];
}

// Tipado Login
export interface LoginData {
    email: string;
    password: string;
}

// Tipado Register
export interface RegisterData {
    name: string;
    lastname: string;
    email: string;
    password: string;
}

export interface ValidateData {
    email: string;
    code: string;
}

// Generated by https://quicktype.io
export interface UserResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    biography: string;
    image:     string;
    state:     boolean;
    role:      string;
    reader:    boolean;
    _id:       string;
    name:      string;
    lastname:  string;
    email:     string;
    date:      string;
    validatorNumber?: number | null
}
