// interface provider
export interface PropsProvider {
    children: JSX.Element | JSX.Element[];
}

// Tipado Login
export interface LoginData {
    email: string;
    password: string;
}

// Tipado Register
export interface RegisterData {
    name: string;
    lastname: string;
    email: string;
    password: string;
}

export interface ValidateData {
    email: string;
    code: string;
}

// Generated by https://quicktype.io
export interface UserResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    biography: string;
    image:     string;
    state:     boolean;
    role:      string;
    reader:    boolean;
    validatorNumber?: number | null
    _id:       string;
    name:      string;
    lastname:  string;
    email:     string;
    date:      string;
}

// Generated by https://quicktype.io

export interface BooksResponse {
    total:     number;
    articulos: Articulo[];
}

export interface BookResponse {
    articulo: Articulo;
}

export interface Articulo {
    description: string;
    image:       string;
    genders:     string[];
    state:       boolean;
    chapter:     Chapter[];
    _id:         string;
    title:       string;
    type:        string;
    progress:    string;
    user:        Usuario;
    date:        string;
    __v:         number;
}


export interface Chapter {
    state:   boolean;
    image:   string;
    _id:     string;
    number:  number;
    title:   string;
    article: string;
    user:    string;
    date:    string;
    __v:     number;
}

export interface SimpArticulo {
    _id:         string;
    title:       string;
    image:       string;
    type:        string;
    chapter:     SimChapter[];
}

export interface SimChapter {
    _id:         string;
    title:       string;
    number:      number;
}
