// interface provider
export interface PropsProvider {
    children: JSX.Element | JSX.Element[];
}



// Generated by https://quicktype.io

export interface UserResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    biography: string;
    image:     string;
    state:     boolean;
    role:      string;
    reader:    boolean;
    _id:       string;
    name:      string;
    lastname:  string;
    email:     string;
    date:      string;
}
